<?php


include_once '../../../common/php/databaseConnection.php';

class fileHandler{

  public function createFile($allCodes){ #this function creates file from random numbers generated by codeGenerator

    $now=date("Y-m-d H:i:s");
    $myfile = fopen("../../../library/codes/".$now.".txt", "w");
    $filename=$now.".txt";

    $headers='Product Series    Product Code'."\n";
    fwrite($myfile,$headers);

    foreach($allCodes as $codesArray){
      $string=$codesArray[0].'    '.$codesArray[1]."\n";
      fwrite($myfile,$string);
    }
    fclose($myfile);

    $rArray=array("../../../library/codes/".$now.".txt",$filename);

    return $rArray;
  }


}

class uploadControll extends fileHandler{

  public function existsInBase($code,$security){
    #Connect
    $db=new askDatabase();
    $sql="SELECT `id` FROM `codes` WHERE `serial`='$code' AND `security`='$security';";
    $status=false;

    #Check if this number is in DB
    $check=$db->getDataFromDatabase($sql);
    $numStatus=is_numeric($check[0][0][0]);

    #Decide if code should be added
    if($numStatus!=true){
      $status=true;
    }

    return $status;
  }

}

class databaseHandle extends uploadControll{

  public function saveToDatabase($codeList){
    #Connect
    $db=new askDatabase();

    #Prepare SQL and Save
    foreach($codeList as $codePack){
      $productSeries=$codePack[0];
      $productCode=$codePack[1];

        if($this->existsInBase($productSeries,$productCode)){
         $sql = "INSERT INTO `codes` (serial, security, uzyty) VALUES ('$productSeries', '$productCode','0')";
        //  echo $sql.'<br/>';
          $db->modifyDataInDatabase($sql);
        }#exists in base end
    }#foreach end

  }#func end

}

?>
